#!/usr/bin/env bash

PREFS_FILE="/etc/apt/preferences.d/snapshot.pref"
tmp_pref_file="/etc/apt/preferences.d/force-testing"
working_dir=$(mktemp -d)
cd $working_dir
apt-get update
apt-get install wget
curl -L -O https://downloads.sourceforge.net/project/kainatos/main/Kainat-kde-settings.deb
dpkg -i ./*.deb

rm -fv /etc/apt/sources.list.d/thorium.list && \
curl -fsSL http://dl.thorium.rocks/debian/dists/stable/thorium.list \
     -o /etc/apt/sources.list.d/thorium.list && \
apt-get update


# Ensure running as root
if [[ $EUID -ne 0 ]]; then
  echo "⚠️  This script must be run as root. Aborting."
  exit 1
fi


# 1. Write the APT pinning preferences
cat > "${PREFS_FILE}" <<EOF
Package: *
Pin: origin "snapshot.debian.org"
Pin-Priority: 1001
EOF
echo "✅ Created APT preferences file at ${PREFS_FILE}"


## 2. Temporary forcing testing release
cat > "${tmp_pref_file}" <<EOF
Package: *
Pin: release a=testing
Pin-Priority: 1001
EOF
echo "✅ done creating Temporary force testing"

# 3. Update APT cache
echo
echo "🔄 Updating APT cache..."
apt-get update

# 4. Perform the dist-upgrade with downgrades
echo
echo "⬇️  Downgrading all packages to snapshot versions..."
apt-get dist-upgrade --allow-downgrades -y -y
apt-get --fix-broken install

apt-get autoremove --purge -y

echo
echo "🎉 upgrade complete. Please reboot and verify system stability."
rm ${PREFS_FILE}
dpkg --add-architecture i386

apt-get update 
apt-get  install linux-headers-amd64 -y
apt-get install kainat-os-core -y
